name: run_xarray_test

on:
  workflow_dispatch:
   
jobs:
  test:
    name: ${{ matrix.os }} py${{ matrix.python-version }} ${{ matrix.env }}
    runs-on: ${{ matrix.os }}
    env:
      REPO_NAME: pydata/xarray
      REPO_PATH: xarray/test
    defaults:
      run:
        shell: bash -l {0}
        working-directory: ${{ env.REPO_PATH }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        # Bookend python versions
        python-version: ["3.12"]
        env: [""]
        include:
          - env: "flaky"
            python-version: "3.12"
            os: ubuntu-latest
    steps:
      - name: Checkout repository ${{ env.REPO_NAME }}
        uses: actions/checkout@v4
        with:
          repository: ${{ env.REPO_NAME }}
          path: ${{ env.REPO_PATH }}
          fetch-depth: 0 # Fetch all history for all branches and tags.
  
      # install miniconda so can install pandoc using conda
      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
          chmod +x Miniconda3-latest-Linux-x86_64.sh
          bash ./Miniconda3-latest-Linux-x86_64.sh -b -p $HOME/miniconda
          conda update -n base -c defaults conda
          conda config --set always_yes yes
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda init
          
      - name: Set environment variables
        run: |
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

          if [[ ${{ matrix.os }} == windows* ]] ;
          then
            if [[ ${{ matrix.python-version }} != "3.13" ]]; then
              echo "CONDA_ENV_FILE=ci/requirements/environment-windows.yml" >> $GITHUB_ENV
            else
              echo "CONDA_ENV_FILE=ci/requirements/environment-windows-3.13.yml" >> $GITHUB_ENV
            fi
          elif [[ "${{ matrix.env }}" != "" ]] ;
          then
            if [[ "${{ matrix.env }}" == "flaky" ]] ;
            then
              echo "CONDA_ENV_FILE=ci/requirements/environment.yml" >> $GITHUB_ENV
              echo "PYTEST_ADDOPTS=-m 'flaky or network' --run-flaky --run-network-tests -W default" >> $GITHUB_ENV
            else
              echo "CONDA_ENV_FILE=ci/requirements/${{ matrix.env }}.yml" >> $GITHUB_ENV
            fi
            if [[ "${{ matrix.env }}" == "min-all-deps" ]] ;
            then
              # Don't raise on warnings
              echo "PYTEST_ADDOPTS=-W default" >> $GITHUB_ENV
            fi
          else
            if [[ ${{ matrix.python-version }} != "3.13" ]]; then
              echo "CONDA_ENV_FILE=ci/requirements/environment.yml" >> $GITHUB_ENV
            else
              echo "CONDA_ENV_FILE=ci/requirements/environment-3.13.yml" >> $GITHUB_ENV
            fi
          fi

          echo "PYTHON_VERSION=${{ matrix.python-version }}" >> $GITHUB_ENV

      # create and activate the conda environment
      - name: Create Conda Environment
        run: |        
          conda info -a
          conda list
          conda create -n xarray-tests python=${{ matrix.python-version }}
          conda env update -n xarray-tests -f ci/requirements/environment.yml
          
      # install python packages
      - name: Install Python Packages
        run: |        
          conda info -a
          conda list
          conda run -n xarray-tests conda install -c conda-forge requests
          conda activate xarray-tests
          #conda run -n xarray-tests pip install .

      - name: Install error reporter
        if: ${{ matrix.os }} == 'ubuntu-latest' and ${{ matrix.python-version }} == '3.12'
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate xarray-tests
          python -m pip install pytest-github-actions-annotate-failures

      - name: Install xarray
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate xarray-tests
          python -m pip install --no-deps -e .

      - name: Version info
        run: |
          conda info -a
          conda list
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate xarray-tests
          conda info -a
          conda list
          python xarray/util/print_versions.py

      - name: Import xarray
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate xarray-tests
          python -c "import xarray"

      - name: Restore cached hypothesis directory
        uses: actions/cache@v4
        with:
          path: .hypothesis/
          key: cache-hypothesis
          enableCrossOsArchive: true
          save-always: true

      - name: Run tests
        run: |
          source $HOME/miniconda/etc/profile.d/conda.sh
          conda activate xarray-tests
          python -m pytest -n 4
          --timeout 180
          --cov=xarray
          --cov-report=xml
          --junitxml=pytest.xml

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test results for ${{ runner.os }}-${{ matrix.python-version }} ${{ matrix.env }}
          path: pytest.xml

